//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//////////////////////////////////////////////////////////


#ifndef edm__DoNotRecordParents_h
#define edm__DoNotRecordParents_h
namespace edm {
class DoNotRecordParents;
} // end of namespace.

#include "Rtypes.h"

namespace edm {
class DoNotRecordParents {

public:
// Nested classes declaration.

public:
// Data Members.

   DoNotRecordParents();
   DoNotRecordParents(DoNotRecordParents && ) = default;
   DoNotRecordParents &operator=(const DoNotRecordParents & );
   DoNotRecordParents(const DoNotRecordParents & );
   virtual ~DoNotRecordParents();

   ClassDef(DoNotRecordParents,11); // Generated by MakeProject.
};
} // namespace
#endif
