//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//////////////////////////////////////////////////////////


#ifndef edm__ViewTypeChecker_h
#define edm__ViewTypeChecker_h
namespace edm {
class ViewTypeChecker;
} // end of namespace.

#include "Rtypes.h"

namespace edm {
class ViewTypeChecker {

public:
// Nested classes declaration.

public:
// Data Members.

   ViewTypeChecker();
   ViewTypeChecker(ViewTypeChecker && ) = default;
   ViewTypeChecker &operator=(const ViewTypeChecker & );
   ViewTypeChecker(const ViewTypeChecker & );
   virtual ~ViewTypeChecker();

   ClassDef(ViewTypeChecker,3); // Generated by MakeProject.
};
} // namespace
#endif
