//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//////////////////////////////////////////////////////////


#ifndef edm__WrapperBase_h
#define edm__WrapperBase_h
namespace edm {
class WrapperBase;
} // end of namespace.

#include "Rtypes.h"
#include "edm__ViewTypeChecker.h"

namespace edm {
class WrapperBase : public edm::ViewTypeChecker {

public:
// Nested classes declaration.

public:
// Data Members.

   WrapperBase();
   WrapperBase(WrapperBase && ) = default;
   WrapperBase &operator=(const WrapperBase & );
   WrapperBase(const WrapperBase & );
   virtual ~WrapperBase();

   ClassDef(WrapperBase,5); // Generated by MakeProject.
};
} // namespace
#endif
