//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//////////////////////////////////////////////////////////


#ifndef FEDRawData_h
#define FEDRawData_h
class FEDRawData;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class FEDRawData {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<unsigned char> data_;

   FEDRawData();
   FEDRawData(FEDRawData && ) = default;
   FEDRawData &operator=(const FEDRawData & );
   FEDRawData(const FEDRawData & );
   virtual ~FEDRawData();

   const unsigned char* data() const { return data_.data(); }
   size_t size() const { return data_.size(); }

   ClassDef(FEDRawData,11); // Generated by MakeProject.
};
#endif
