//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//////////////////////////////////////////////////////////


#ifndef FEDRawDataCollection_h
#define FEDRawDataCollection_h
class FEDRawDataCollection;

#include "Rtypes.h"
#include "edm__DoNotRecordParents.h"
#include "Riostream.h"
#include <vector>
#include "FEDRawData.h"

class FEDRawDataCollection : public edm::DoNotRecordParents {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<FEDRawData> data_;       // the raw data

   FEDRawDataCollection();
   FEDRawDataCollection(FEDRawDataCollection && ) = default;
   FEDRawDataCollection &operator=(const FEDRawDataCollection & );
   FEDRawDataCollection(const FEDRawDataCollection & );
   virtual ~FEDRawDataCollection();

   ClassDef(FEDRawDataCollection,12); // Generated by MakeProject.
};
#endif
